# Generated by Django 5.0.4 on 2024-05-01 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Low', 'LOW'), ('Medium', 'MEDIUM'), ('High', 'HIGH'), ('Critical', 'CRITICAL')], max_length=20)),
                ('message', models.TextField()),
                ('acknowledge', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Domain', 'DOMAIN'), ('IP Address', 'IP_ADDRESS'), ('Port', 'PORT')], max_length=20)),
                ('description', models.CharField(max_length=250, null=True)),
                ('value', models.CharField(max_length=500, unique=True)),
                ('checkValue', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('parser', models.CharField(choices=[('json', 'JSON'), ('txt', 'TXT'), ('csv', 'CSV')], max_length=10)),
                ('refresh', models.DurationField()),
                ('delimeter', models.CharField(blank=True, default=None, max_length=1, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category')),
            ],
        ),
    ]
