# Generated by Django 5.0.4 on 2024-04-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Domain', 'DOMAIN'), ('IP Address', 'IP_ADDRESS')], max_length=20)),
                ('value', models.CharField(max_length=500)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField()),
            ],
        ),
    ]
