# Generated by Django 5.0.4 on 2024-04-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
