# Generated by Django 5.0.4 on 2024-04-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='type',
            new_name='parser',
        ),
        migrations.AddField(
            model_name='alert',
            name='acknowledge',
            field=models.BooleanField(default=False),
        ),
    ]
