# Generated by Django 5.0.4 on 2024-05-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_helper_is_sniffer_running_helper_sniffer_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helper',
            name='is_using_rsync',
            field=models.BooleanField(default=False),
        ),
    ]
